# Generated by Django 4.2.4 on 2023-08-11 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_citacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion',
            name='lugar',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citacion',
            name='tenida',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citacion',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='citacion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
