# Generated by Django 4.2.4 on 2023-08-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_alter_citacion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacion',
            name='descripcion',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
