# Generated by Django 4.2.4 on 2023-08-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_citacion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(max_length=15),
        ),
    ]
