# Generated by Django 4.2.5 on 2023-09-15 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0007_licencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencia',
            name='fecha_licencia',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
