# Generated by Django 4.2.5 on 2023-12-26 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0008_licencia_fecha_licencia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licencia',
            options={'permissions': [('check_licencias', 'Puede revisar todas las licencias')]},
        ),
    ]
