# Generated by Django 4.2.5 on 2024-01-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0010_tipodocumento_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
