# Generated by Django 4.2.5 on 2024-01-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0011_alter_documento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodocumento',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
