# Generated by Django 4.2.5 on 2024-01-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0012_alter_tipodocumento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(default='logos/logo.png', upload_to='docs/'),
        ),
    ]
