# Generated by Django 4.2.5 on 2024-01-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0015_alter_documento_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='nombre_original',
            field=models.CharField(default='peo', max_length=500),
            preserve_default=False,
        ),
    ]
