# Generated by Django 4.2.5 on 2024-01-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0016_documento_nombre_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodocumento',
            name='slug',
            field=models.CharField(default='peo', max_length=100),
            preserve_default=False,
        ),
    ]
