# Generated by Django 4.2.5 on 2024-01-23 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0019_documento_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='ruta',
            field=models.CharField(max_length=500),
        ),
    ]
