# Generated by Django 4.2.5 on 2024-01-23 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0020_alter_documento_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='ruta',
        ),
    ]
