# Generated by Django 4.2.5 on 2024-01-23 02:44

from django.db import migrations, models
import intranet.validators


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0021_remove_documento_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='docs/', validators=[intranet.validators.file_size, intranet.validators.validate_file_extension]),
        ),
    ]
