# Generated by Django 4.2.5 on 2024-01-28 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import intranet.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0023_userprofile_contacto_userprofile_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='documentos/', validators=[intranet.validators.file_size, intranet.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='imagen',
            field=models.ImageField(default='fotos_perfil/user.jpg', upload_to='fotos_perfil/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bombero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('numero_comprobante', models.IntegerField(null=True)),
                ('fecha_ingreso', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
