# Generated by Django 4.2.5 on 2024-01-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0024_alter_documento_archivo_alter_userprofile_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='numero_comprobante',
            field=models.TextField(null=True),
        ),
    ]
