# Generated by Django 4.2.5 on 2024-01-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0025_alter_cuota_numero_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='numero_comprobante',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
